
#=========================================
# GAM(M)-MAP LOADED PACKAGES
#=========================================

library(readxl)
library(shiny)
library(sf)
library(shinydashboard)
library(shinyjs)
library(shinyBS)        
library(DT)             
library(plotly)         
library(ggplot2)        
library(dplyr)          
library(tidyr)          
library(lubridate)      
library(mgcv)           
library(gratia)         
library(gridExtra)      
library(markdown)       
library(htmltools)      
library(stats)          
library(tidyverse)      
library(leaflet)        
library(reshape2)       
library(shinycssloaders) 
library(nlme)   
library(MASS)   
library(gt)
