
### Checks for required packages and installs if not present ###

library(shiny)
library(tidyverse)
library(dplyr)
library(gridExtra)
library(tseries)
library(forecast)
library(lubridate)
library(ggplot2)
library(ggfortify)
library(zoo)
library(TSA)
library(mgcv)
library(readr)
library(plotly)
library(doParallel)
library(shinyWidgets)
library(readr)    
library(psych)
library(DT)
library(shinyalert)
library(shinythemes)
library(shinycssloaders)
library(shinyjs)
library(bsplus)
library(adaptivetau)  # ssa.maketrans()
library(bsplus)  # bs_accordion(), use_bs_accordion_sidebar()
library(data.table)  # rbindlist()
library(deSolve)  # ode()
library(highcharter)  # hchart()
library(Rcpp)  # sourceCpp()
library(readxl)  # read_excel()
library(shinyBS)  # bsModal()
library(sortable)  #  bucket_list()
library(RColorBrewer)  # brewer.pal()
library(scales)  # scales()
library(shinyhelper)  # helper()
library(tidyverse)  # mutate()
library(vov)  # blur_in()
library(lmtest)
library(gt)
library(jsonlite)
library(htmltools)
library(pdftools)
library(remotes)
library(shinybusy)
library(plotly)
library(gratia)
library(ggeffects)
library(markdown)
library(sf) 
library(leaflet)
library(stats)
library(reshape2)
library(pdftools)
library(rcompanion)
library(PMCMRplus)
library(dunn.test)
library(cowplot)
library(itsadug)   #GAMM and bam acf plot
library(shinydashboard)



