
---
title: "about_page_5"
author: "Edward"
date: "2026-03-04"
output: html_document
---


### Authors & Affiliations

---

| Author | Affiliation | Role |
|--------|-------------|------|
| **Edward Akurugu** ⭐ | Modelling and Simulation Hub, Africa (MASHA), Department of Statistical Sciences, University of Cape Town, Cape Town, South Africa | Principal Investigator, Corresponding Author |
| **Sheetal Prakash Silal** | MASHA, University of Cape Town; Centre for Global Health, University of Oxford, UK | Lead Supervisor |
| **Timothy Awine** | Navrongo Health Research Centre, Navrongo, Ghana | Co‑Supervisor |
| **Baba Seidu** | Department of Mathematics, C.K. Tedam University of Technology and Applied Sciences, Navrongo, Ghana | Co‑Supervisor |
| **Nana Yaw Peprah** | National Malaria Elimination Program, Ghana Health Service, Accra, Ghana | Data Provider (NMEP) |
| **Wahjib Mohammed** | National Malaria Elimination Program, Ghana Health Service, Accra, Ghana | Data Provider (NMEP) |
| **Paul Boateng** | National Malaria Elimination Program, Ghana Health Service, Accra, Ghana | Data Provider (NMEP) |
| **Dr. Paul Hilarius Asiwome Kosi Abiwu** | National Malaria Elimination Program, Ghana Health Service, Accra, Ghana | Data Provider (NMEP) |

---

### ✉️ Corresponding Author

**Edward Akurugu**  
📧 [akredw001@myuct.ac.za](mailto:akredw001@myuct.ac.za) | [akuruguedward@gmail.com](mailto:akuruguedward@gmail.com)

⭐ = Corresponding author
