---
title: "help_page_4"
author: "Edward"
date: "2025-03-04"
output: html_document
---

<div style="color:green; ">
General Usage:
</div>

- Use Chrome or Firefox for best performance
- Desktop/laptop recommended for full visualisation
- Allow 1–5 seconds for data and models to load

<div style="color:green; ">
Data Selection:
</div>

- Select specific regions for detailed analysis
- Compare multiple regions by switching selections
- Use the full date range (2012–2023) for comprehensive trends


<div style="color:green; ">
Interpreting Results:
</div>

- Higher adjusted R² and deviance explained values indicate a better model fit (closer to 100%) under GAMs  
- Lower AIC, BIC, and higher adjusted R² (closer to 100%) values indicate a better model fit under GAMMs  
- Significant p‑values (< 0.05) indicate important predictors under GAM and GAMM estimates  
- Seasonal patterns reveal peak malaria months  
- Higher concurvity values (≥ 0.8) indicate strong collinearity among smooth terms  
- Non‑significant p‑values in tests of serial autocorrelation under GAMs and GAMMs indicate that residuals are independent (no autocorrelation present)  

---
